create table coverage_option (
    id int8 generated by default as identity,
    option varchar(255),
    coverage_option_id int8,
    primary key (id)
                             );

alter table if exists coverage_option
    add constraint coverage_option_fk foreign key (coverage_option_id)
    references personal_policy